# Set theme
remote_theme: daviddarnes/alembic@main

# 1. File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# 2. Installed Gems / Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# 3. Gem settings
paginate: 5
paginate_path: blog/page:num

# 4. Jekyll settings
timezone: America/Vancouver # use IANA time zone database

# 5. Collections
collections:
  posts:
    title: Blog
    output: true
    description: ""
    feature_text: ''
    feature_image: "/assets/header.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
url: 'https://erindarrow.github.io'
baseurl: ''
title: 'Erin Darrow'
description: 'Fantasy author'
permalink: pretty
logo: "/assets/logo.png"
lang: "en-US"
email: ""
disqus: ""
css_inline: false # if true, will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
      
# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  
# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Writing
  url: /writing/
- title: Blog
  url: /blog/
- title: Contact
  url: /contact/
- title: Search
  url: /search/

navigation_footer:
- title: RSS feed
  url: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Email: true
  Twitter: "#815F93"
  facebook: "#815F93"
  tumblr: "#815F93"
  Email: true

# 10. Fonts
# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Heebo&family=Lora&display=swap
